{"uuid": "1d2a0ba5-c9f2-436a-86c6-64910c07fc4c", "children": ["0fe23405-ceed-4c74-b1d9-c8f5e6048d5a", "ef8b2e13-5ef3-4fa0-9f49-8dbc7aa30d00", "46391d62-8fe7-4239-a0bd-472f614553ff", "7eea0027-54b5-4f86-812f-d13d5ed07656", "589a11fe-fc25-4535-b7f7-39a3d99abc6a", "b033fd2f-9092-46c1-bd1e-02496d6d057e", "3b5bdce6-5d79-403a-b8cc-fcbbdadc3be5", "86dd98e7-1dbc-4e51-8637-c42762602ee3", "62735fe6-1fca-4bae-a33c-bee4ac2c259f", "33cd995b-15fd-4a98-ba06-cf6aa793949d", "bce5cfc0-0f52-4d82-b8cd-ac25103bcb75", "ab183c1b-f83b-497f-a330-153626945832", "6f1e81eb-dd2c-4a4a-90d2-b743c2c07ca1", "d2955b85-96b0-46ce-a9ea-eb2d82e6a52d", "1ac80ed7-8fd5-4ab7-b0f8-ec424f1cf0c6", "d4ce2396-1bb0-4e16-b107-c9e20423c77d", "e1f71306-f11e-4218-beb9-4026745e90b6", "582aa46c-0d8b-4361-ab02-636476e85edb", "5fea1a05-dd70-4a65-a9a7-fb3031efd47c", "c41b00a0-c7cd-4cc9-a652-cb3e3c5f7b84", "6bfb16fb-226e-4267-be5c-4c4534622d73", "df690de1-55ed-417b-974e-e671ad7b804f", "f0f681a5-9014-4294-bd45-85cafbbfeb08", "1e692f24-2967-4723-94a3-51ae07b7b01f", "ff80b183-2e39-4628-8ab0-9397eb22dd1d", "3d27768d-1e24-4245-a811-a90f847ca0fe"], "befores": [{"name": "start_session", "status": "broken", "statusDetails": {"message": "sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')\n(Background on this error at: http://sqlalche.me/e/e3q8)\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/renata/PycharmProjects/final_progect/conftest.py\", line 66, in start_session\n    MysqlOrmBuilder(MysqlOrmConnection('root', 'renata', 'users'))\n  File \"/Users/renata/PycharmProjects/final_progect/orm/orm_client.py\", line 14, in __init__\n    self.connection = self.connect()\n  File \"/Users/renata/PycharmProjects/final_progect/orm/orm_client.py\", line 37, in connect\n    connection = self.get_connection()\n  File \"/Users/renata/PycharmProjects/final_progect/orm/orm_client.py\", line 34, in get_connection\n    return engine.connect()\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 2193, in connect\n    return self._connection_cls(self, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 103, in __init__\n    else engine.raw_connection()\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 2293, in raw_connection\n    self.pool.unique_connection, _connection\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 2266, in _wrap_pool_connect\n    e, dialect, self\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 1536, in _handle_dbapi_exception_noconnection\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py\", line 383, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py\", line 128, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py\", line 2262, in _wrap_pool_connect\n    return fn()\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 294, in unique_connection\n    return _ConnectionFairy._checkout(self)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 751, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 483, in checkout\n    rec = pool._do_get()\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py\", line 138, in _do_get\n    self._dec_overflow()\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py\", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py\", line 129, in reraise\n    raise value\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py\", line 135, in _do_get\n    return self._create_connection()\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 299, in _create_connection\n    return _ConnectionRecord(self)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 428, in __init__\n    self.__connect(first_connect_check=True)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py\", line 630, in __connect\n    connection = pool._invoke_creator(self)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py\", line 114, in connect\n    return dialect.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py\", line 453, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python3.7/site-packages/pymysql/__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/pymysql/connections.py\", line 325, in __init__\n    self.connect()\n  File \"/usr/local/lib/python3.7/site-packages/pymysql/connections.py\", line 598, in connect\n    self._get_server_information()\n  File \"/usr/local/lib/python3.7/site-packages/pymysql/connections.py\", line 975, in _get_server_information\n    packet = self._read_packet()\n  File \"/usr/local/lib/python3.7/site-packages/pymysql/connections.py\", line 657, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"/usr/local/lib/python3.7/site-packages/pymysql/connections.py\", line 707, in _read_bytes\n    CR.CR_SERVER_LOST, \"Lost connection to MySQL server during query\")\n"}, "start": 1590608847720, "stop": 1590608889087}], "start": 1590608847720, "stop": 1590608916301}